In [3]:
import numpy as np
arr = np.array([1,2,4,5])
print(arr.dtype)


int32


In [9]:
arr=np.array([1,2,3,4],dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
arr = np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [11]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
#1D
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
print(z)


In [1]:
#2D
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x represents the 2-D array:")
  print(x)


x represents the 2-D array:
[[1 2 3]
 [4 5 6]]
x represents the 2-D array:
[[ 7  8  9]
 [10 11 12]]


In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)
      

1
2
3
4
5
6


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [6]:
import numpy as np
a=np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])

b=np.array([2,4,6,8])
print("\n printing array a..")
print(a)
print("\n printing array b..")
print(b)
print("\n adding arrays a and b..")
c=a+b;
print (c)


 printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

 printing array b..
[2 4 6 8]

 adding arrays a and b..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [ ]:
#vstack
