In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [3]:
#0D
arr = np.array(45)
print(arr)

45


In [4]:
#1D
arr= np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
#2D
arr= np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [6]:
#3D
arr= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
a = np.array(45)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
arr = np.array([1,2,3,4,5],ndmin=5)
print(arr)
print('number of dim :',arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dim : 5


NameError: name 'np' is not defined