In [1]:

from scipy.stats import circmean
 

print(circmean([0.4, 2.4, 3.6], high=4, low=2))

2.254068341376122


In [2]:
from scipy.stats.contingency import crosstab
 

a = ['A', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B']
 

p = ['P', 'P', 'P', 'Q', 'R', 'R', 'Q', 'Q', 'R', 'R']
 

print(crosstab(a, p))
 

(auv, puv), cnt = crosstab(a,  p)

print(auv)

print(puv)
 
print(cnt)

CrosstabResult(elements=(array(['A', 'B'], dtype='<U1'), array(['P', 'Q', 'R'], dtype='<U1')), count=array([[2, 3, 0],
       [1, 0, 4]]))
['A' 'B']
['P' 'Q' 'R']
[[2 3 0]
 [1 0 4]]


In [3]:
from scipy import stats as st
import numpy as npy
array = npy.array([10, 20, 30, 40, 50, 60, 70, 80])
print(st.describe(array))

DescribeResult(nobs=8, minmax=(10, 80), mean=45.0, variance=600.0, skewness=0.0, kurtosis=-1.2380952380952381)


In [4]:
from scipy import stats as st
array = [[2, 3], [3, 1], [1, 3],\
         [3, 3], [4, 2], [4, 4],\
         [1, 2], [5, 6]]
print(st.mode(array))

ModeResult(mode=array([1, 3], dtype=int64), count=array([2, 3], dtype=int64))


In [5]:
from scipy import stats as st
import numpy as npy
array = npy.array([10, 20, 30, 40, 50, 60, 70, 80])
print(st.describe(array))

DescribeResult(nobs=8, minmax=(10, 80), mean=45.0, variance=600.0, skewness=0.0, kurtosis=-1.2380952380952381)


In [6]:
import numpy as np
from scipy.stats import norm
print(norm.cdf(npy.array([-2, 0, 2])))

[0.02275013 0.5        0.97724987]


In [7]:
from scipy import stats as st
array = [2, 3, 15, 1, 6, 9, 8, 4, 5, 10]
print(st.rankdata(array))

[ 2.  3. 10.  1.  6.  8.  7.  4.  5.  9.]
